apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweis-quantum-bank-backend-deployment
  namespace: tweis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweis-quantum-bank-backend-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tweis-quantum-bank-backend-deployment
    spec:
      containers:
      - name: quantum-bank-backend
        image: {{.Values.image}}  
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
